environment:
  matrix:
    - nodejs_version: '5'
    - nodejs_version: '4'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

matrix:
  fast_finish: true

build: off

shallow_clone: true

test_script:
  - node --version
  - npm --version
  - npm run test:ci

cache:
  - '%APPDATA%\npm-cache'

notifications:
  - provider: Email
    to:
      - '{{APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL}}'
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
