environment:
  matrix:
    - nodejs_version: 'Current'
    - nodejs_version: 'LTS'
    - nodejs_version: '10'
    - nodejs_version: '9'
    - nodejs_version: '8'
    - nodejs_version: '7'
    - nodejs_version: '6'
    - nodejs_version: '5'
    - nodejs_version: '4'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

matrix:
  fast_finish: true

build: off

shallow_clone: true

test_script:
  - node --version
  - npm --version
  - npm run test:ci

cache:
  - '%APPDATA%\npm-cache'
